[package]
name = "rust_foundations"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = ["authentication", "deadlocks", "divide_work", "footgun", "hello", "login", "login_manager", "mutexes", "rwlocks", "scoped_threads", "thread_builder",
    "variables",
]


